In [422]:
import pandas as pd 
import numpy as np
import matplotlib as plt
import seaborn as sns
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report , accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

In [423]:
df = pd.read_csv('insurance.csv')
df

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
0,67,119.8,1.56,2.92000,False,Jaipur,retired,High
1,36,101.1,1.83,34.28000,False,Chennai,freelancer,Low
2,39,56.8,1.64,36.64000,False,Indore,freelancer,Low
3,22,109.4,1.55,3.34000,True,Mumbai,student,Medium
4,69,62.2,1.60,3.94000,True,Indore,retired,High
...,...,...,...,...,...,...,...,...
95,36,52.8,1.57,19.64000,False,Indore,business_owner,Low
96,26,113.8,1.54,34.01000,False,Delhi,private_job,Low
97,52,60.8,1.80,44.86000,False,Hyderabad,freelancer,Low
98,27,101.1,1.82,28.30000,False,Kolkata,business_owner,Low
99,40,70.0,1.59,28.16664,True,Bangalore,government_job,Low

In [424]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   age                         100 non-null    int64
 1   weight                      100 non-null    float64
 2   height                      100 non-null    float64
 3   income_lpa                  100 non-null    float64
 4   smoker                      100 non-null    bool
 5   city                        100 non-null    object
 6   occupation                  100 non-null    object
 7   insurance_premium_category  100 non-null    object
dtypes: bool(1), float64(3), int64(1), object(3)
memory usage: 5.7+ KB

In [425]:
from sklearn.preprocessing import OneHotEncoder

In [426]:
df

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
0,67,119.8,1.56,2.92000,False,Jaipur,retired,High
1,36,101.1,1.83,34.28000,False,Chennai,freelancer,Low
2,39,56.8,1.64,36.64000,False,Indore,freelancer,Low
3,22,109.4,1.55,3.34000,True,Mumbai,student,Medium
4,69,62.2,1.60,3.94000,True,Indore,retired,High
...,...,...,...,...,...,...,...,...
95,36,52.8,1.57,19.64000,False,Indore,business_owner,Low
96,26,113.8,1.54,34.01000,False,Delhi,private_job,Low
97,52,60.8,1.80,44.86000,False,Hyderabad,freelancer,Low
98,27,101.1,1.82,28.30000,False,Kolkata,business_owner,Low
99,40,70.0,1.59,28.16664,True,Bangalore,government_job,Low

In [427]:
df['bmi'] = df['weight'] / (df['height'] ** 2)
df

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,bmi
0,67,119.8,1.56,2.92000,False,Jaipur,retired,High,49.227482
1,36,101.1,1.83,34.28000,False,Chennai,freelancer,Low,30.189017
2,39,56.8,1.64,36.64000,False,Indore,freelancer,Low,21.118382
3,22,109.4,1.55,3.34000,True,Mumbai,student,Medium,45.535900
4,69,62.2,1.60,3.94000,True,Indore,retired,High,24.296875
...,...,...,...,...,...,...,...,...,...
95,36,52.8,1.57,19.64000,False,Indore,business_owner,Low,21.420747
96,26,113.8,1.54,34.01000,False,Delhi,private_job,Low,47.984483
97,52,60.8,1.80,44.86000,False,Hyderabad,freelancer,Low,18.765432
98,27,101.1,1.82,28.30000,False,Kolkata,business_owner,Low,30.521676
99,40,70.0,1.59,28.16664,True,Bangalore,government_job,Low,27.688778

In [428]:
def lifestyle_risk(row):
    if row['smoker'] and row['bmi'] > 30:
        return 'high risk'
    elif row['smoker'] or row['bmi'] > 27:
        return 'medium risk'
    else:
        return 'low risk'

In [429]:
df['lifestyle_risk'] = df.apply(lifestyle_risk , axis = 1)

In [430]:
df

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,bmi,lifestyle_risk
0,67,119.8,1.56,2.92000,False,Jaipur,retired,High,49.227482,medium risk
1,36,101.1,1.83,34.28000,False,Chennai,freelancer,Low,30.189017,medium risk
2,39,56.8,1.64,36.64000,False,Indore,freelancer,Low,21.118382,low risk
3,22,109.4,1.55,3.34000,True,Mumbai,student,Medium,45.535900,high risk
4,69,62.2,1.60,3.94000,True,Indore,retired,High,24.296875,medium risk
...,...,...,...,...,...,...,...,...,...,...
95,36,52.8,1.57,19.64000,False,Indore,business_owner,Low,21.420747,low risk
96,26,113.8,1.54,34.01000,False,Delhi,private_job,Low,47.984483,medium risk
97,52,60.8,1.80,44.86000,False,Hyderabad,freelancer,Low,18.765432,low risk
98,27,101.1,1.82,28.30000,False,Kolkata,business_owner,Low,30.521676,medium risk
99,40,70.0,1.59,28.16664,True,Bangalore,government_job,Low,27.688778,medium risk

In [431]:
def age_group(age):
    if age < 25:
        return 'young'
    elif age < 45:
        return 'adult'
    elif age < 60:
        return 'middle_aged'
    else:
        return 'senior'

In [432]:
df['age_group'] = df['age'].apply(age_group)
df

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,bmi,lifestyle_risk,age_group
0,67,119.8,1.56,2.92000,False,Jaipur,retired,High,49.227482,medium risk,senior
1,36,101.1,1.83,34.28000,False,Chennai,freelancer,Low,30.189017,medium risk,adult
2,39,56.8,1.64,36.64000,False,Indore,freelancer,Low,21.118382,low risk,adult
3,22,109.4,1.55,3.34000,True,Mumbai,student,Medium,45.535900,high risk,young
4,69,62.2,1.60,3.94000,True,Indore,retired,High,24.296875,medium risk,senior
...,...,...,...,...,...,...,...,...,...,...,...
95,36,52.8,1.57,19.64000,False,Indore,business_owner,Low,21.420747,low risk,adult
96,26,113.8,1.54,34.01000,False,Delhi,private_job,Low,47.984483,medium risk,adult
97,52,60.8,1.80,44.86000,False,Hyderabad,freelancer,Low,18.765432,low risk,middle_aged
98,27,101.1,1.82,28.30000,False,Kolkata,business_owner,Low,30.521676,medium risk,adult
99,40,70.0,1.59,28.16664,True,Bangalore,government_job,Low,27.688778,medium risk,adult

In [433]:
df['occupation'].unique()

array(['retired', 'freelancer', 'student', 'government_job',
       'business_owner', 'unemployed', 'private_job'], dtype=object)

In [434]:
df['city'].unique()

array(['Jaipur', 'Chennai', 'Indore', 'Mumbai', 'Kota', 'Hyderabad',
       'Delhi', 'Chandigarh', 'Pune', 'Kolkata', 'Lucknow', 'Gaya',
       'Jalandhar', 'Mysore', 'Bangalore'], dtype=object)

In [435]:
tier_1 = ['Chennai' , 'Delhi' , 'Mumbai' , 'Kolkata' , 'Pune' , 'Hyderabad' , 'Bangalore']
tier_2 = ['Jaipur' , 'Indore' , 'Kota' , 'Lucknow' , 'Chandigarh' , 'Jalandhar' , 'Mysore']

def city_tier(city):
    if city in tier_1:
        return 1
    elif city in tier_2:
        return 2
    else:
        return 3

In [436]:
df['city_tier'] = df['city'].apply(city_tier)

In [437]:
df

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,bmi,lifestyle_risk,age_group,city_tier
0,67,119.8,1.56,2.92000,False,Jaipur,retired,High,49.227482,medium risk,senior,2
1,36,101.1,1.83,34.28000,False,Chennai,freelancer,Low,30.189017,medium risk,adult,1
2,39,56.8,1.64,36.64000,False,Indore,freelancer,Low,21.118382,low risk,adult,2
3,22,109.4,1.55,3.34000,True,Mumbai,student,Medium,45.535900,high risk,young,1
4,69,62.2,1.60,3.94000,True,Indore,retired,High,24.296875,medium risk,senior,2
...,...,...,...,...,...,...,...,...,...,...,...,...
95,36,52.8,1.57,19.64000,False,Indore,business_owner,Low,21.420747,low risk,adult,2
96,26,113.8,1.54,34.01000,False,Delhi,private_job,Low,47.984483,medium risk,adult,1
97,52,60.8,1.80,44.86000,False,Hyderabad,freelancer,Low,18.765432,low risk,middle_aged,1
98,27,101.1,1.82,28.30000,False,Kolkata,business_owner,Low,30.521676,medium risk,adult,1
99,40,70.0,1.59,28.16664,True,Bangalore,government_job,Low,27.688778,medium risk,adult,1

In [438]:
df1 = df[['income_lpa' , 'bmi' , 'age_group' , 'lifestyle_risk' , 'city_tier' , 'occupation' , 'insurance_premium_category']]

In [439]:
df1

,income_lpa,bmi,age_group,lifestyle_risk,city_tier,occupation,insurance_premium_category
0,2.92000,49.227482,senior,medium risk,2,retired,High
1,34.28000,30.189017,adult,medium risk,1,freelancer,Low
2,36.64000,21.118382,adult,low risk,2,freelancer,Low
3,3.34000,45.535900,young,high risk,1,student,Medium
4,3.94000,24.296875,senior,medium risk,2,retired,High
...,...,...,...,...,...,...,...
95,19.64000,21.420747,adult,low risk,2,business_owner,Low
96,34.01000,47.984483,adult,medium risk,1,private_job,Low
97,44.86000,18.765432,middle_aged,low risk,1,freelancer,Low
98,28.30000,30.521676,adult,medium risk,1,business_owner,Low
99,28.16664,27.688778,adult,medium risk,1,government_job,Low

In [440]:
x = df1[['bmi' , 'income_lpa' , 'age_group' , 'lifestyle_risk' , 'city_tier' , 'occupation']]
y = df1['insurance_premium_category']

In [441]:
categorical_feat = ['age_group' , 'lifestyle_risk' , 'city_tier' , 'occupation']
numerical_feat = ['bmi' , 'income_lpa']

In [442]:
from sklearn.compose import ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('cat' , OneHotEncoder() , categorical_feat),
        ('num' , 'passthrough' , numerical_feat)
    ]
)

In [443]:
pipeline = Pipeline(steps = [
    ('preprocessor' , preprocessor),
    ('classifier' , RandomForestClassifier(random_state=42))
])

In [444]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 1)
pipeline.fit(x_train , y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('cat', OneHotEncoder(),
                                                  ['age_group',
                                                   'lifestyle_risk',
                                                   'city_tier', 'occupation']),
                                                 ('num', 'passthrough',
                                                  ['bmi', 'income_lpa'])])),
                ('classifier', RandomForestClassifier(random_state=42))])

In [445]:
y_pred = pipeline.predict(x_test)
accuracy_score(y_test , y_pred)

0.8

In [446]:
import pickle

pickle_model_path = 'model.pkl'
with open(pickle_model_path , 'wb') as f:
    pickle.dump(pipeline , f)